### PR TITLE
Add docker collection to the requirements.yml

### LINKED ISSUE #297: Ansible-lint not able to find docker collection
We need to define the docker collection in the requirements.yml too.

### PR DESCRIPTION
**Pull request by ra-beer**
Ansible-lint fails because it can´t find the docker collection.
This patch will add it to the requirements.
Closes #297

Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

### CODE REVIEW

**Review by ppkuschy — APPROVED** [review]
LGTM

**Comment by ra-beer** [comment]
recheck

**Comment by ra-beer** [comment]
recheck

**Comment by ra-beer** [comment]
recheck

**Review by ppkuschy — APPROVED** [review]
LGTM

**Pull request merged**
