### PR TITLE
Use kubernetes_monitoring role in kubernetes-monitoring play

### PR DESCRIPTION
**Pull request by matofeder**
Related PRs
- https://github.com/osism/defaults/pull/181
- https://github.com/osism/ansible-collection-services/pull/1434

SCS issue: https://github.com/SovereignCloudStack/issues/issues/576

### CODE REVIEW

**Comment by matofeder** [comment]
@berendt 
attention: 

When `hosts: localhost, connection: local` are used the default variables defined within https://github.com/osism/defaults/pull/181/files are not applied! 

This is a known issue and should be resolved, before merging. 
One possible solution could be the creation of a `localhost` inventory group as a child group for `manager`:
```
[localhost:children]
manager
```

then the inventory graph looks like:

```
/# ansible-inventory -i inventory/hosts.yml localhost --graph 

@localhost:
  |--@manager:
  |  |--@testbed-managers:
  |  |  |--testbed-manager.testbed.osism.xyz
```

hence, the `localhost` group will inherit the testbed-manager.testbed.osism.xyz defaults.
Alternatively, we could use the `manager` host directly in the playbook. 
But I'm not sure whether it is a good approach, (e.g. could OSISM have more than 1 manager nodes?)

**Comment by matofeder** [comment]
@berendt 
if there is not a better solution for the above issue https://github.com/osism/ansible-playbooks/pull/420#issuecomment-2137301141, I can create a similar deployment-specific (testbed) configuration file, similar to the rook: https://github.com/osism/testbed/blob/rook/environments/rook/configuration.yml

**Comment by berendt** [comment]
I'll be back on Wednesday and will have a look at the localhost problem etc.. Sorry for the delay here.

**Comment by berendt** [comment]
Recheck

**Pull request merged**
