### PR TITLE
Jtorres/example setup proxy realm

### PR DESCRIPTION
**Pull request by JuanPTM**
[Example setup issue](https://github.com/SovereignCloudStack/issues/issues/596)

The keycloak configuration will be a default example of how the proxy approach should work. There is still one small problem with the login flow requirements, It's commented on this draft but it needs to be fixed before merge.

### CODE REVIEW

**Comment by JuanPTM** [comment]
This requieres https://github.com/SovereignCloudStack/container-images/pull/8 to be merged first. As it requires the script to be inside the scs-keycloak image

**Comment by berendt** [comment]
@JuanPTM How to proceed here?

**Comment by JuanPTM** [comment]
> @JuanPTM How to proceed here?

I've squash everything.
I think this can be merged, maybe some issues may appear if the wrong keycloak image is used

**Comment by berendt** [comment]
Please fix all yamllint and ansilbe-lint issues.

**Pull request merged**
